# src/morningstar_modbus/catalog/families/genstar_mppt.py
"""GenStar MPPT register catalog."""

from morningstar_modbus.catalog.types import DeviceProfileSpec, RegisterBlock, RegisterSpec

SOURCE = (
    "https://www.morningstarcorp.com/wp-content/uploads/"
    "technical-doc-genstar-mppt-modbus-specification-en.pdf"
)

CHARGE_STATES = (
    (0, "STARTING"),
    (1, "NIGHT_CHECK"),
    (2, "DISCONNECTED"),
    (3, "NIGHT"),
    (4, "FAULT"),
    (5, "BULK"),
    (6, "ABSORPTION"),
    (7, "FLOAT"),
    (8, "EQUALIZE"),
)
LOAD_STATES = (
    (0, "START"),
    (1, "NORMAL"),
    (2, "LVD_WARNING"),
    (3, "LVD"),
    (4, "FAULT"),
    (5, "DISCONNECT"),
    (6, "NORMAL_OFF"),
    (7, "OVERRIDE"),
)
SYSTEM_FAULTS = (
    (0, "eeprom_chip_failure"),
    (2, "software_fault"),
    (3, "no_model_number"),
    (6, "eeprom_settings_edit"),
    (8, "bms_required"),
    (10, "software_reset"),
    (15, "adc_overrun"),
    (16, "adc_no_injection"),
    (17, "adc_double_injection"),
    (18, "battery_shunt_missing"),
    (29, "eeprom_settings_bad"),
    (30, "hardware_failure"),
)
ALARMS = (
    (0, "rts_open"),
    (1, "rts_shorted"),
    (2, "rts_disconnected"),
    (3, "heatsink_sensor_open"),
    (4, "heatsink_sensor_shorted"),
    (5, "heatsink_overtemp_limiting"),
    (6, "current_limiting"),
    (7, "battery_current_offset"),
    (8, "battery_sense_error"),
    (9, "battery_sense_disconnected"),
    (10, "uncalibrated"),
    (11, "rts_near_5v"),
    (17, "high_array_voltage_current_limit"),
    (23, "array_current_offset"),
    (24, "eeprom_bus_failure"),
    (25, "ethernet_hardware"),
    (26, "entered_lvd"),
    (27, "software_runtime_error"),
    (29, "external_flash_failure"),
    (32, "inductor_current_offset"),
    (33, "coin_cell_low"),
    (35, "rtc_wrong"),
    (36, "rtc_hardware"),
    (37, "casting_temp_sensor_open"),
    (38, "casting_temp_sensor_short"),
    (39, "inductor_casting_overtemp"),
    (41, "wireless_module_failure"),
    (42, "hardware_error_post_startup"),
    (43, "unknown_block_type"),
    (44, "readyblock_1_hardware"),
    (45, "readyblock_2_hardware"),
    (46, "readyblock_3_hardware"),
    (50, "generator_start_failed"),
    (51, "backup_generator_start_failed"),
    (52, "schedule_publisher_failed"),
    (53, "processor_uncalibrated"),
    (54, "load_current_offset"),
    (55, "load_fet_stuck_open"),
    (56, "bms_sense_error"),
    (57, "bms_sense_disconnected"),
)
LOAD_FAULTS = (
    (0, "load_software"),
    (1, "load_overcurrent"),
    (2, "load_external_short"),
    (3, "load_power_supply"),
    (4, "load_hvd"),
    (5, "load_heatsink_overtemp"),
    (6, "load_fet_shorted"),
    (7, "load_system"),
)
CHARGE_FAULTS = (
    (0, "software_bug"),
    (1, "battery_hvd"),
    (2, "rts_shorted"),
    (3, "rts_disconnected"),
    (4, "slave_mode_timeout"),
)

GENSTAR_MPPT = DeviceProfileSpec(
    name="genstar_mppt",
    family="GenStar MPPT",
    aliases=("genstar mppt", "gs-mppt", "gsmppt"),
    source_id="genstar-mppt-modbus-v03",
    source_url=SOURCE,
    detection_priority=1,
    blocks=(
        RegisterBlock(0x0000, 0x0006, category="metadata", cache=True),
        RegisterBlock(0x001F, 0x001A),
        RegisterBlock(0x0063, 0x0003),
        RegisterBlock(0x0075, 0x0005),
        RegisterBlock(0x0080, 0x0001),
        RegisterBlock(0x00B1, 0x0007),
        RegisterBlock(0x00E0, 0x000B),
        RegisterBlock(0x00F0, 0x0005),
        RegisterBlock(0x0100, 0x0011),
        # Current and daily system-fault/alarm/charge-fault words are contiguous.
        RegisterBlock(0x0212, 0x0018),
        # Morningstar v03 documents a gap at 0x026F-0x0270, so keep logger reads split.
        RegisterBlock(0x026A, 0x0005),
        RegisterBlock(0x0271, 0x0009),
        RegisterBlock(0x02A0, 0x0002),
        # System and internal charge counters are separately contiguous source-backed blocks.
        RegisterBlock(0x02D0, 0x000C),
        RegisterBlock(0x02E8, 0x000C),
    ),
    registers=(
        RegisterSpec("firmware_version", 0x0000, category="metadata"),
        RegisterSpec(
            "serial_number",
            0x0001,
            words=4,
            decoder="ascii_hi_lo",
            category="metadata",
        ),
        RegisterSpec("software_patchlevel", 0x0005, category="metadata"),
        RegisterSpec("load_current", 0x001F, decoder="f16", unit="A"),
        RegisterSpec("array_current", 0x0020, decoder="f16", unit="A"),
        RegisterSpec("battery_terminal_voltage", 0x0021, decoder="f16", unit="V"),
        RegisterSpec("array_voltage", 0x0022, decoder="f16", unit="V"),
        RegisterSpec("load_voltage", 0x0023, decoder="f16", unit="V"),
        RegisterSpec("battery_sense_voltage", 0x0025, decoder="f16", unit="V"),
        RegisterSpec("casting_temp", 0x002A, decoder="f16", unit="C"),
        RegisterSpec("coin_cell_voltage", 0x0036, decoder="f16", unit="V"),
        RegisterSpec("system_charge_current", 0x0063, decoder="f16", unit="A"),
        RegisterSpec("system_battery_current", 0x0064, decoder="f16", unit="A"),
        RegisterSpec("system_load_current", 0x0065, decoder="f16", unit="A"),
        RegisterSpec("battery_temp", 0x0075, decoder="f16", unit="C"),
        RegisterSpec("rts_temp", 0x0076, decoder="f16", unit="C"),
        RegisterSpec("heatsink_temp", 0x0077, decoder="f16", unit="C"),
        RegisterSpec("inductor_casting_temp", 0x0078, decoder="f16", unit="C"),
        RegisterSpec("internal_temp", 0x0079, decoder="f16", unit="C"),
        RegisterSpec("charge_state", 0x0080, category="state", enum=CHARGE_STATES),
        RegisterSpec("target_voltage", 0x00B1, decoder="f16", unit="V"),
        RegisterSpec("bms_mode", 0x00B2, category="state"),
        RegisterSpec("slave_target_voltage", 0x00B4, decoder="f16", unit="V"),
        RegisterSpec(
            "max_array_current",
            0x00B5,
            decoder="f16",
            unit="A",
            category="metadata",
        ),
        RegisterSpec(
            "max_charge_current",
            0x00B6,
            decoder="f16",
            unit="A",
            category="metadata",
        ),
        RegisterSpec(
            "max_battery_current",
            0x00B7,
            decoder="f16",
            unit="A",
            category="metadata",
        ),
        RegisterSpec("battery_soc", 0x00E0, decoder="f16_percent", unit="%"),
        RegisterSpec("battery_voltage_min", 0x00E1, decoder="f16", unit="V"),
        RegisterSpec("battery_voltage_max", 0x00E2, decoder="f16", unit="V"),
        RegisterSpec("output_power", 0x00F0, decoder="f16", unit="W"),
        RegisterSpec("vmp", 0x00F1, decoder="f16", unit="V"),
        RegisterSpec("pmax", 0x00F2, decoder="f16", unit="W"),
        RegisterSpec("voc", 0x00F3, decoder="f16", unit="V"),
        RegisterSpec("array_voltage_reference", 0x00F4, decoder="f16", unit="V"),
        RegisterSpec("load_state", 0x0100, category="state", enum=LOAD_STATES),
        RegisterSpec(
            "load_faults",
            0x0101,
            words=2,
            decoder="bitfield_words",
            category="fault",
            bits=LOAD_FAULTS,
        ),
        RegisterSpec(
            "system_faults",
            0x0212,
            words=4,
            decoder="bitfield_words",
            category="fault",
            bits=SYSTEM_FAULTS,
        ),
        RegisterSpec(
            "system_faults_daily",
            0x0216,
            words=4,
            decoder="bitfield_words",
            category="fault",
            bits=SYSTEM_FAULTS,
            description="System faults accumulated in the controller's current daily log.",
        ),
        RegisterSpec(
            "alarms",
            0x021A,
            words=4,
            decoder="bitfield_words",
            category="alarm",
            bits=ALARMS,
        ),
        RegisterSpec(
            "alarms_daily",
            0x021E,
            words=4,
            decoder="bitfield_words",
            category="alarm",
            bits=ALARMS,
            description="Alarms accumulated in the controller's current daily log.",
        ),
        RegisterSpec(
            "charge_faults",
            0x0222,
            words=4,
            decoder="bitfield_words",
            category="fault",
            bits=CHARGE_FAULTS,
        ),
        RegisterSpec(
            "charge_faults_daily",
            0x0226,
            words=4,
            decoder="bitfield_words",
            category="fault",
            bits=CHARGE_FAULTS,
            description="Charge faults accumulated in the controller's current daily log.",
        ),
        RegisterSpec(
            "battery_voltage_min_hourly",
            0x026A,
            decoder="f16",
            unit="V",
            description="Minimum battery voltage for the controller's current hourly log.",
        ),
        RegisterSpec(
            "battery_voltage_max_hourly",
            0x026B,
            decoder="f16",
            unit="V",
            description="Maximum battery voltage for the controller's current hourly log.",
        ),
        RegisterSpec(
            "battery_voltage_min_daily",
            0x026C,
            decoder="f16",
            unit="V",
            description="Minimum battery voltage for the controller's current daily log.",
        ),
        RegisterSpec(
            "battery_voltage_max_daily",
            0x026D,
            decoder="f16",
            unit="V",
            description="Maximum battery voltage for the controller's current daily log.",
        ),
        RegisterSpec(
            "array_voltage_max_daily",
            0x026E,
            decoder="f16",
            unit="V",
            description="Maximum array voltage for the controller's current daily log.",
        ),
        RegisterSpec(
            "output_power_max_daily",
            0x0271,
            decoder="f16",
            unit="W",
            description="Maximum output power for the controller's current daily log.",
        ),
        RegisterSpec(
            "battery_temp_min_daily",
            0x0272,
            decoder="f16",
            unit="C",
            description=(
                "Minimum battery temperature in the daily log. Morningstar v03 labels the "
                "table unit as V while naming/describing this value as battery temperature."
            ),
        ),
        RegisterSpec(
            "battery_temp_max_daily",
            0x0273,
            decoder="f16",
            unit="C",
            description=(
                "Maximum battery temperature in the daily log. Morningstar v03 labels the "
                "table unit as V while naming/describing this value as battery temperature."
            ),
        ),
        RegisterSpec(
            "absorption_seconds_daily",
            0x0274,
            words=2,
            decoder="f32",
            unit="s",
            description="Seconds spent in Absorption during the current daily log period.",
        ),
        RegisterSpec(
            "equalize_seconds_daily",
            0x0276,
            words=2,
            decoder="f32",
            unit="s",
            description="Seconds spent in Equalize during the current daily log period.",
        ),
        RegisterSpec(
            "float_seconds_daily",
            0x0278,
            words=2,
            decoder="f32",
            unit="s",
            description="Seconds spent in Float during the current daily log period.",
        ),
        RegisterSpec("led_state", 0x02A0, category="state"),
        RegisterSpec("soc_led_state", 0x02A1, category="state"),
        RegisterSpec(
            "system_charge_kwh_daily",
            0x02D0,
            words=2,
            decoder="f32",
            unit="kWh",
            description="System-wide charge energy accumulated today.",
        ),
        RegisterSpec(
            "system_charge_kwh_resettable",
            0x02D2,
            words=2,
            decoder="u32_factor:0.1",
            unit="kWh",
            description="System-wide resettable charge-energy counter.",
        ),
        RegisterSpec(
            "system_charge_kwh_total",
            0x02D4,
            words=2,
            decoder="u32_factor:0.1",
            unit="kWh",
            description="System-wide lifetime charge-energy counter.",
        ),
        RegisterSpec(
            "system_charge_ah_daily",
            0x02D6,
            words=2,
            decoder="f32",
            unit="Ah",
            description="System-wide charge amp-hours accumulated today.",
        ),
        RegisterSpec(
            "system_charge_ah_resettable",
            0x02D8,
            words=2,
            decoder="u32_factor:0.1",
            unit="Ah",
            description="System-wide resettable charge amp-hour counter.",
        ),
        RegisterSpec(
            "system_charge_ah_total",
            0x02DA,
            words=2,
            decoder="u32_factor:0.1",
            unit="Ah",
            description="System-wide lifetime charge amp-hour counter.",
        ),
        RegisterSpec(
            "internal_charge_kwh_daily",
            0x02E8,
            words=2,
            decoder="f32",
            unit="kWh",
            description="This controller's internal charge energy accumulated today.",
        ),
        RegisterSpec(
            "internal_charge_kwh_resettable",
            0x02EA,
            words=2,
            decoder="u32_factor:0.1",
            unit="kWh",
            description="This controller's resettable internal charge-energy counter.",
        ),
        RegisterSpec(
            "internal_charge_kwh_total",
            0x02EC,
            words=2,
            decoder="u32_factor:0.1",
            unit="kWh",
            description="This controller's lifetime internal charge-energy counter.",
        ),
        RegisterSpec(
            "internal_charge_ah_daily",
            0x02EE,
            words=2,
            decoder="f32",
            unit="Ah",
            description="This controller's internal charge amp-hours accumulated today.",
        ),
        RegisterSpec(
            "internal_charge_ah_resettable",
            0x02F0,
            words=2,
            decoder="u32_factor:0.1",
            unit="Ah",
            description="This controller's resettable internal charge amp-hour counter.",
        ),
        RegisterSpec(
            "internal_charge_ah_total",
            0x02F2,
            words=2,
            decoder="u32_factor:0.1",
            unit="Ah",
            description="This controller's lifetime internal charge amp-hour counter.",
        ),
    ),
    capabilities=(
        "rtu",
        "usb",
        "rs232",
        "eia485",
        "modbus_tcp",
        "ethernet",
        "wifi",
        "bluetooth",
        "charge",
        "load",
        "readyrail",
        "device_identification",
        "hourly_logger_summary",
        "daily_logger_summary",
        "event_logger",
        "sd_logging",
        "snmp_polling",
    ),
    network=(
        ("baudrate", "9600"),
        ("stop_bits", "1"),
        ("tcp_port", "502"),
        ("default_modbus_id", "1"),
        ("dhcp", "enabled"),
        ("fallback_ip", "192.168.1.251"),
        ("netbios", "GSMPPT<serial>"),
    ),
)
