# src/morningstar_modbus/catalog/families/tristar_mppt.py
"""TriStar MPPT 150V register catalog."""

from morningstar_modbus.catalog.common import (
    TRISTAR_MPPT_ALARMS,
    TRISTAR_MPPT_CHARGE_STATES,
    TRISTAR_MPPT_DAILY_FLAGS,
    TRISTAR_MPPT_FAULTS,
    TRISTAR_MPPT_LED_STATES,
)
from morningstar_modbus.catalog.types import DeviceProfileSpec, RegisterBlock, RegisterSpec

SOURCE = (
    "https://www.morningstarcorp.com/wp-content/uploads/"
    "technical-doc-tristar-mppt-modbus-specification-en.pdf"
)

DIP_SWITCH_BITS = tuple((bit, f"switch_{bit + 1}_on") for bit in range(8))

TRISTAR_MPPT = DeviceProfileSpec(
    name="tristar_mppt",
    family="TriStar MPPT 150V",
    aliases=("tristar mppt", "ts-mppt-45", "ts-mppt-60", "tsmppt"),
    source_id="tristar-mppt-modbus-v11",
    source_url=SOURCE,
    detection_priority=20,
    blocks=(
        RegisterBlock(0x0000, 0x0050),
        RegisterBlock(0xE0C0, 0x000E, category="metadata", optional=True, cache=True),
    ),
    registers=(
        RegisterSpec(
            "voltage_scale_hi",
            0x0000,
            category="metadata",
            description="Whole-number portion of the controller voltage scaling constant.",
        ),
        RegisterSpec(
            "voltage_scale_lo",
            0x0001,
            category="metadata",
            description="Fractional portion of the controller voltage scaling constant.",
        ),
        RegisterSpec(
            "current_scale_hi",
            0x0002,
            category="metadata",
            description="Whole-number portion of the controller current scaling constant.",
        ),
        RegisterSpec(
            "current_scale_lo",
            0x0003,
            category="metadata",
            description="Fractional portion of the controller current scaling constant.",
        ),
        RegisterSpec(
            "firmware_version",
            0x0004,
            decoder="bcd",
            category="metadata",
            description="Controller software/firmware version reported by the TriStar MPPT.",
        ),
        RegisterSpec(
            "battery_voltage",
            0x0018,
            decoder="tristar_voltage",
            unit="V",
            description="Filtered battery voltage measured internally by the controller.",
        ),
        RegisterSpec(
            "battery_terminal_voltage",
            0x0019,
            decoder="tristar_voltage",
            unit="V",
            description="Filtered voltage measured at the controller battery terminals.",
        ),
        RegisterSpec(
            "battery_sense_voltage",
            0x001A,
            decoder="tristar_voltage",
            unit="V",
            description="Filtered remote battery-sense voltage used to compensate for wiring voltage drop.",
        ),
        RegisterSpec(
            "array_voltage",
            0x001B,
            decoder="tristar_voltage",
            unit="V",
            description="Filtered solar-array input voltage.",
        ),
        RegisterSpec(
            "battery_charge_current",
            0x001C,
            decoder="tristar_current",
            unit="A",
            description="Filtered charging current delivered toward the battery.",
        ),
        RegisterSpec(
            "array_current",
            0x001D,
            decoder="tristar_current",
            unit="A",
            description="Filtered solar-array input current.",
        ),
        RegisterSpec(
            "supply_12v_voltage",
            0x001E,
            decoder="factor:0.0005679931640625",
            unit="V",
            description="Filtered internal 12 V supply rail voltage used for controller diagnostics.",
        ),
        RegisterSpec(
            "supply_3v_voltage",
            0x001F,
            decoder="factor:0.000201416015625",
            unit="V",
            description="Filtered internal 3 V supply rail voltage used for controller diagnostics.",
        ),
        RegisterSpec(
            "meterbus_voltage",
            0x0020,
            decoder="factor:0.0005679931640625",
            unit="V",
            description="Filtered MeterBus supply voltage.",
        ),
        RegisterSpec(
            "supply_1v8_voltage",
            0x0021,
            decoder="factor:0.000091552734375",
            unit="V",
            description="Filtered internal 1.8 V supply rail voltage used for controller diagnostics.",
        ),
        RegisterSpec(
            "reference_voltage",
            0x0022,
            decoder="factor:0.000091552734375",
            unit="V",
            description="Internal ADC reference voltage used for controller diagnostics.",
        ),
        RegisterSpec(
            "heatsink_temp",
            0x0023,
            decoder="s16",
            unit="C",
            description="Controller heatsink temperature.",
        ),
        RegisterSpec(
            "rts_temp",
            0x0024,
            decoder="tristar_rts_temp",
            unit="C",
            description="Remote Temperature Sensor reading; reports disconnected when the RTS is absent.",
        ),
        RegisterSpec(
            "battery_temp",
            0x0025,
            decoder="s16",
            unit="C",
            description="Battery regulation temperature used for temperature-compensated charging.",
        ),
        RegisterSpec(
            "battery_voltage_1m",
            0x0026,
            decoder="tristar_voltage",
            unit="V",
            description="Approximately one-minute filtered battery voltage, useful for stable thresholds.",
        ),
        RegisterSpec(
            "charge_current_1m",
            0x0027,
            decoder="tristar_current",
            unit="A",
            description="Approximately one-minute filtered charging current.",
        ),
        RegisterSpec(
            "battery_voltage_min",
            0x0028,
            decoder="tristar_voltage",
            unit="V",
            description="Lowest battery voltage retained by the resettable controller statistics.",
        ),
        RegisterSpec(
            "battery_voltage_max",
            0x0029,
            decoder="tristar_voltage",
            unit="V",
            description="Highest battery voltage retained by the resettable controller statistics.",
        ),
        RegisterSpec(
            "operating_hours",
            0x002A,
            words=2,
            decoder="u32",
            unit="h",
            description="Total controller operating time in hours.",
        ),
        RegisterSpec(
            "faults",
            0x002C,
            category="fault",
            bits=TRISTAR_MPPT_FAULTS,
            description="Currently active controller fault conditions decoded from the fault bitfield.",
        ),
        RegisterSpec(
            "alarms",
            0x002E,
            words=2,
            decoder="u32",
            category="alarm",
            bits=TRISTAR_MPPT_ALARMS,
            description="Currently active controller alarm conditions decoded from the two-word alarm bitfield.",
        ),
        RegisterSpec(
            "dip_switches",
            0x0030,
            category="state",
            bits=DIP_SWITCH_BITS,
            description="Physical DIP switch positions; bit 0 corresponds to settings switch 1.",
        ),
        RegisterSpec(
            "led_state",
            0x0031,
            category="state",
            enum=TRISTAR_MPPT_LED_STATES,
            description="Current front-panel LED indication state.",
        ),
        RegisterSpec(
            "charge_state",
            0x0032,
            category="state",
            enum=TRISTAR_MPPT_CHARGE_STATES,
            description="Current charging stage such as MPPT, Absorption, Float, or Equalize.",
        ),
        RegisterSpec(
            "target_voltage",
            0x0033,
            decoder="tristar_voltage",
            unit="V",
            description="Current battery regulation target after charge-stage and temperature compensation.",
        ),
        RegisterSpec(
            "charge_ah_resettable",
            0x0034,
            words=2,
            decoder="u32_factor:0.1",
            unit="Ah",
            description="Solar amp-hours accumulated since the resettable energy counters were cleared.",
        ),
        RegisterSpec(
            "charge_ah_total",
            0x0036,
            words=2,
            decoder="u32_factor:0.1",
            unit="Ah",
            description="Lifetime cumulative solar charging amp-hours.",
        ),
        RegisterSpec(
            "charge_kwh_resettable",
            0x0038,
            unit="kWh",
            description="Solar charging energy accumulated since the resettable energy counters were cleared.",
        ),
        RegisterSpec(
            "charge_kwh_total",
            0x0039,
            unit="kWh",
            description="Lifetime cumulative solar charging energy in kilowatt-hours.",
        ),
        RegisterSpec(
            "output_power",
            0x003A,
            decoder="tristar_power",
            unit="W",
            description="Instantaneous charging power delivered from the controller toward the battery.",
        ),
        RegisterSpec(
            "input_power",
            0x003B,
            decoder="tristar_power",
            unit="W",
            description="Estimated instantaneous power entering from the solar array.",
        ),
        RegisterSpec(
            "sweep_max_power",
            0x003C,
            decoder="tristar_power",
            unit="W",
            description="Maximum power found during the most recent MPPT sweep.",
        ),
        RegisterSpec(
            "sweep_vmp",
            0x003D,
            decoder="tristar_voltage",
            unit="V",
            description="Array voltage at maximum power from the most recent MPPT sweep.",
        ),
        RegisterSpec(
            "sweep_voc",
            0x003E,
            decoder="tristar_voltage",
            unit="V",
            description="Array open-circuit voltage measured during the most recent MPPT sweep.",
        ),
        RegisterSpec(
            "daily_battery_voltage_min",
            0x0040,
            decoder="tristar_voltage",
            unit="V",
            description="Lowest battery voltage recorded during the current charging day.",
        ),
        RegisterSpec(
            "daily_battery_voltage_max",
            0x0041,
            decoder="tristar_voltage",
            unit="V",
            description="Highest battery voltage recorded during the current charging day.",
        ),
        RegisterSpec(
            "daily_array_voltage_max",
            0x0042,
            decoder="tristar_voltage",
            unit="V",
            description="Highest solar-array input voltage recorded during the current charging day.",
        ),
        RegisterSpec(
            "daily_charge_ah",
            0x0043,
            decoder="ufactor:0.1",
            unit="Ah",
            description="Total charging amp-hours accumulated during the current charging day.",
        ),
        RegisterSpec(
            "daily_charge_wh",
            0x0044,
            decoder="ufactor:10",
            unit="Wh",
            description="Total charging energy accumulated today; the controller reports this in 10 Wh steps.",
        ),
        RegisterSpec(
            "daily_flags",
            0x0045,
            category="state",
            bits=TRISTAR_MPPT_DAILY_FLAGS,
            description="Sticky daily event flags for reset, equalize, float, alarm, and fault events.",
        ),
        RegisterSpec(
            "daily_output_power_max",
            0x0046,
            decoder="tristar_power",
            unit="W",
            description="Highest charging output power recorded during the current charging day.",
        ),
        RegisterSpec(
            "daily_battery_temp_min",
            0x0047,
            decoder="s16",
            unit="C",
            description="Lowest battery temperature recorded during the current charging day.",
        ),
        RegisterSpec(
            "daily_battery_temp_max",
            0x0048,
            decoder="s16",
            unit="C",
            description="Highest battery temperature recorded during the current charging day.",
        ),
        RegisterSpec(
            "daily_faults",
            0x0049,
            category="fault",
            bits=TRISTAR_MPPT_FAULTS,
            description="Sticky fault conditions that occurred at least once during the current charging day.",
        ),
        RegisterSpec(
            "daily_alarms",
            0x004B,
            words=2,
            decoder="u32",
            category="alarm",
            bits=TRISTAR_MPPT_ALARMS,
            description="Sticky alarm conditions that occurred at least once during the current charging day.",
        ),
        RegisterSpec(
            "daily_absorption_seconds",
            0x004D,
            unit="s",
            description="Cumulative time spent in Absorption during the current charging day.",
        ),
        RegisterSpec(
            "daily_equalize_seconds",
            0x004E,
            unit="s",
            description="Cumulative time spent in Equalize during the current charging day.",
        ),
        RegisterSpec(
            "daily_float_seconds",
            0x004F,
            unit="s",
            description="Cumulative time spent in Float during the current charging day.",
        ),
        RegisterSpec(
            "serial_number",
            0xE0C0,
            words=4,
            decoder="ascii_lo_hi",
            category="metadata",
            description="Controller serial number from the read-only factory metadata area.",
        ),
        RegisterSpec(
            "model_flag",
            0xE0CC,
            category="metadata",
            enum=((0, "TS-MPPT-45"), (1, "TS-MPPT-60")),
            description="Factory model identifier distinguishing the 45 A and 60 A TriStar MPPT variants.",
        ),
        RegisterSpec(
            "hardware_version",
            0xE0CD,
            category="metadata",
            description="Controller hardware revision from the read-only factory metadata area.",
        ),
    ),
    capabilities=("rtu", "rs232", "eia485", "modbus_tcp", "ethernet", "device_identification"),
    network=(
        ("tcp_port", "502"),
        ("default_modbus_id", "1"),
        ("dhcp", "enabled"),
        ("fallback_ip", "192.168.1.253"),
        ("netbios", "tsmppt<serial>"),
    ),
)
